#define ALPHA_LOWER "abcdefghijklmnopqrstuvwxyz"
#define ALPHA_UPPER "ABCDEFGHIJKLMNPQRSTUVWXYZ"
#define NUMBERS "0123456789"
#define CHAR_ALL "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNPQRSTUVWXYZ0123456789"
#define NOUN_FILE "nouns"
#define ADJ_FILE "adjectives"